[package]
name = "dev_caloptreyx_mint"
description = "A dark theme for Calagopus Panel with a live, built-in theme editor."
authors = ["Caloptreyx"]
version = "2.0.0"
edition = { workspace = true }

[dependencies]
shared = { workspace = true }
async-trait = { workspace = true }
tracing = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
utoipa = { workspace = true }
utoipa-axum = { workspace = true }
compact_str = { workspace = true }
anyhow = { workspace = true }
axum = { workspace = true }
tokio = { workspace = true }
uuid = { workspace = true }
semver = { workspace = true }
image = { version = "0.25.5", default-features = false, features = ["png", "jpeg", "webp", "gif"] }
